### ISSUE TITLE
Cannot enter number in OTP View

### ISSUE THREAD

**Issue by SharankumarKsk** [rajputmukesh748/MukeshOtpView#1]
I used the OTPView, But I am Unable to enter number in OTP view.

**Comment by rajputmukesh748** [comment]
Hi SharanKumarKsk
Please add style in your project (Already given in Documentation Please Check.)

<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="mukeshOtpStyle">@style/OtpWidget.OtpView</item>
</style>


<style name="OtpWidget.OtpView" parent="Widget.AppCompat.EditText">
    <item name="android:background">@null</item>
    <item name="android:minHeight">0dp</item>
    <item name="android:maxLines">1</item>
</style>

Thank you.

**Comment by rajputmukesh748** [comment]
Hope your issue is resolved.
