### ISSUE TITLE
Can't type anything

### ISSUE THREAD

**Issue by Softkeydel** [rajputmukesh748/MukeshOtpView#2]
Is this View Read Only View?
How to type something from keyboard and take that input to MukeshOtpView
Please help

**Comment by rajputmukesh748** [comment]
Hi @Softkeydel 
Please add style to your project theme file. Then it will work. also, make sure you give hint in XML FIle, not text.

Theme File Code Add for Keyboard.

```
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="mukeshOtpStyle">@style/OtpWidget.OtpView</item>
</style>

<style name="OtpWidget.OtpView" parent="Widget.AppCompat.EditText">
    <item name="android:background">@null</item>
    <item name="android:minHeight">0dp</item>
    <item name="android:maxLines">1</item>
</style>

```

Thank you.

**Comment by Softkeydel** [comment]
@rajputmukesh748 
Thanks

**Comment by rajputmukesh748** [comment]
Welcome @Softkeydel
