### ISSUE TITLE
Keyboard not opening at all

### ISSUE THREAD

**Issue by manu-tursunov** [rajputmukesh748/MukeshOtpView#3]

**Comment by rajputmukesh748** [comment]
Hi 
Please add below style in your theme file.

<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <item name="mukeshOtpStyle">@style/OtpWidget.OtpView</item>
</style>


<style name="OtpWidget.OtpView" parent="Widget.AppCompat.EditText">
    <item name="android:background">@null</item>
    <item name="android:minHeight">0dp</item>
    <item name="android:maxLines">1</item>
</style>

Thank you.
