### ISSUE TITLE
Keyboard Issue

### ISSUE THREAD

**Issue by DevNoLimit** [rajputmukesh748/MukeshOtpView#4]
Keyboard Not Opening in otp view

**Comment by rajputmukesh748** [comment]
Hi
Please add below style in your theme file.

<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar"> @style/OtpWidget.OtpView </style> <style name="OtpWidget.OtpView" parent="Widget.AppCompat.EditText"> @null 0dp 1 </style>
Thank you.
